### ISSUE TITLE
Error in URL

### ISSUE THREAD

**Issue by tkurc** [SBU-BMI/FeatureScapeToolSuite#1]
There is an error in the FeatureScapeApps URL linked from quip1.bmi.stonybrook.edu.

Clicking on the “Go!” button on the FeatureScape page will get the following URL:

http://sbu-bmi.github.io/FeatureScapeApps/featurescape//u24Preview.html#http://quip1.uhmc.sunysb.edu:3000

The double “//“ before u24Preview.html causes the URL to fall to load data.

**Comment by tdiprima** [comment]
Fixed.  

You can test it with [simple url](http://sbu-bmi.github.io/FeatureScapeApps/featurescape/).  

Or [url query string](http://sbu-bmi.github.io/FeatureScapeApps/featurescape/?http://quip1.uhmc.sunysb.edu:3000/?limit=1000&find={"randval":{"$gte":0.497},"provenance.analysis.execution_id":"luad:bg:20160520","provenance.analysis.source":"computer","provenance.image.subject_id":"TCGA-05-4397"}&db=u24_luad&c=luad).

Tested in Chrome, Firefox, and Safari.
